kind: pipeline
type: docker
name: Docker image build
trigger:
  branch:
    - master
environment:
  VERSION: 4.13.5
steps:
  - name: config
    image: alpine
    commands:
      - echo -n "$VERSION,latest" > .tags
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/samba